# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NSU Spots
email: your-email@domain.com
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb

permalink: pretty

collections:
  spots_de:
    output: true
    permalink: /de/spots/:name/
  spots_en:
    output: true
    permalink: /en/spots/:name/
  spots_tr:
    output: true
    permalink: /tr/spots/:name/
  pages_de:
    output: false
  pages_en:
    output: false
  pages_tr:
    output: false

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: '_spots_de'
      type: 'spots_de'
    values:
      lang: 'de'
  - scope:
      path: '_spots_en'
      type: 'spots_en'
    values:
      lang: 'en'
  - scope:
      path: '_spots_tr'
      type: 'spots_tr'
    values:
      lang: 'tr'
  - scope:
      path: '_pages_de'
      type: 'pages_de'
    values:
      lang: 'de'
  - scope:
      path: '_pages_en'
      type: 'pages_en'
    values:
      lang: 'en'
  - scope:
      path: '_pages_tr'
      type: 'pages_tr'
    values:
      lang: 'tr'

# Build settings
markdown: kramdown

prose:
  media: 'images'
  metadata:
    _spots_de:
      - name: 'youtube_id'
        field:
          element: 'text'
          label: 'Youtube-ID'
    _spots_en:
      - name: 'youtube_id'
        field:
          element: 'text'
          label: 'Youtube-ID'
    _spots_tr:
      - name: 'youtube_id'
        field:
          element: 'text'
          label: 'Youtube-ID'
  ignore:
    - '_includes'
    - '_layouts'
    - 'assets'
    - 'src'
    - '.gitignore'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'gulpfile.js'
    - 'package.json'
    - 'webpack.config.js'
    - 'LICENSE'
    - '_config.yml'
    - 'data.json'
    - 'index.md'

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js
  - webpack.config.js
  - src
