# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NSU Spots
email: your-email@domain.com
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/nsu-spots" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb

permalink: pretty

collections:
  videos_de:
    output: true
    permalink: /de/spots/:name/
  videos_en:
    output: true
    permalink: /en/spots/:name/
  videos_tr:
    output: true
    permalink: /tr/spots/:name/

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: 'de'
      type: 'pages'
    values:
      is_page: true
      lang: 'de'
  - scope:
      path: 'en'
      type: 'pages'
    values:
      is_page: true
      lang: 'en'
  - scope:
      path: 'tr'
      type: 'pages'
    values:
      is_page: true
      lang: 'tr'
  - scope:
      path: ''
      type: 'videos_de'
    values:
      is_video: true
      lang: 'de'
  - scope:
      path: ''
      type: 'videos_en'
    values:
      is_video: true
      lang: 'en'
  - scope:
      path: ''
      type: 'videos_tr'
    values:
      is_video: true
      lang: 'tr'

# Build settings
markdown: kramdown

prose:
  metadata:
    _spots:
      - name: 'number'
        field:
          element: 'text'
          label: 'Nummer'
      - name: 'title_de'
        field:
          element: 'text'
          label: 'Titel (DE)'
      - name: 'title_tr'
        field:
          element: 'text'
          label: 'Titel (TR)'
      - name: 'title_en'
        field:
          element: 'text'
          label: 'Titel (EN)'
      - name: 'youtube_id'
        field:
          element: 'text'
          label: 'Youtube-ID'

  ignore:
    - '_includes'
    - '_layouts'
    - 'assets'
    - 'src'
    - '.gitignore'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'gulpfile.js'
    - 'package.json'
    - 'webpack.config.js'

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js
  - webpack.config.js
  - src
